Repository ThalesGroup/fred, pull requests merged in 2025-09, with the labels that each got.

#446 443 update the tabular output processor to enhance the date column handling
  knowledge_flow_backend/app/common/structures.py
  knowledge_flow_backend/app/core/processors/output/tabular_processor/tabular_processor.py
Labels: enhancement

#486 add profile to resources and profile selector
  agentic_backend/app/core/agents/agent_state.py
  agentic_backend/app/core/agents/flow.py
  agentic_backend/app/core/agents/runtime_context.py
  frontend/src/components/ConfirmationDialogProvider.tsx
  frontend/src/components/chatbot/ChatBot.tsx
  frontend/src/components/chatbot/ChatResourcesSelectionCard.tsx
  frontend/src/components/chatbot/PluginSelector.tsx
  frontend/src/components/chatbot/Settings.tsx
  frontend/src/components/chatbot/settings/ProfilePickerPanel.tsx
  frontend/src/components/chatbot/user_input/UserInput.tsx
  frontend/src/components/documents/libraries/DocumentLibraryList.tsx
  frontend/src/components/resources/ProfileEditorModal.tsx
  frontend/src/components/resources/PromptEditorModal.tsx
  frontend/src/components/resources/ResourceLibraryList.tsx
  frontend/src/components/resources/TemplateEditorModal.tsx
  frontend/src/components/resources/resourceYamlUtils.ts
  frontend/src/locales/en/translation.json
  frontend/src/locales/fr/translation.json
  frontend/src/pages/Chat.tsx
  frontend/src/pages/KnowledgeHub.tsx
  frontend/src/slices/agentic/agenticOpenApi.ts
  frontend/src/slices/knowledgeFlow/knowledgeFlowOpenApi.ts
  knowledge_flow_backend/app/features/resources/structures.py
  knowledge_flow_backend/app/features/tag/service.py
  knowledge_flow_backend/app/features/tag/structure.py
Labels: enhancement

#553 Move minio access key from env var to settings in configuration
  knowledge_flow_backend/app/common/structures.py
  knowledge_flow_backend/config/.env.template
  knowledge_flow_backend/config/configuration_prod.yaml
  knowledge_flow_backend/config/configuration_worker.yaml
Labels: bug

#574 Improve ollama setup
  README.md
Labels: documentation

#576 Fix issue with circular imports in fred core and docker ignore
  .dockerignore
  agentic_backend/app/application_context.py
  agentic_backend/app/common/structures.py
  agentic_backend/app/core/logs_controller.py
  agentic_backend/app/main.py
  fred-core/fred_core/__init__.py
  fred-core/fred_core/logs/__init__.py
  frontend/.dockerignore
  knowledge_flow_backend/app/application_context.py
  knowledge_flow_backend/app/common/structures.py
  knowledge_flow_backend/app/features/kpi/logs_controller.py
  knowledge_flow_backend/app/main.py
Labels: bug
